// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
	"time"
)

const createApiKey = `-- name: CreateApiKey :one

INSERT INTO api_keys (name, key_hash, created_by) VALUES (?, ?, ?) RETURNING id, name, key_hash, created_by, last_used_at, created_at
`

type CreateApiKeyParams struct {
	Name      string `json:"name"`
	KeyHash   string `json:"key_hash"`
	CreatedBy int64  `json:"created_by"`
}

// Only the SHA-256 of a Content API key is stored, so the plaintext is shown
// once at creation and never again.
func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createApiKey, arg.Name, arg.KeyHash, arg.CreatedBy)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteApiKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteApiKey, id)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, name, key_hash, created_by, last_used_at, created_at FROM api_keys WHERE key_hash = ?
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT k.id, k.name, k.key_hash, k.created_by, k.last_used_at, k.created_at, u.name AS created_by_name
FROM api_keys k JOIN users u ON u.id = k.created_by
ORDER BY k.created_at DESC
`

type ListApiKeysRow struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	KeyHash       string     `json:"key_hash"`
	CreatedBy     int64      `json:"created_by"`
	LastUsedAt    *time.Time `json:"last_used_at"`
	CreatedAt     time.Time  `json:"created_at"`
	CreatedByName string     `json:"created_by_name"`
}

func (q *Queries) ListApiKeys(ctx context.Context) ([]ListApiKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchApiKey = `-- name: TouchApiKey :exec
UPDATE api_keys SET last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ?
`

func (q *Queries) TouchApiKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchApiKey, id)
	return err
}
