// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
)

const countMedia = `-- name: CountMedia :one
SELECT count(*) FROM media
`

func (q *Queries) CountMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (key, filename, url, mime, size, uploaded_by, alt)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, "key", filename, url, mime, size, uploaded_by, created_at, alt
`

type CreateMediaParams struct {
	Key        string `json:"key"`
	Filename   string `json:"filename"`
	Url        string `json:"url"`
	Mime       string `json:"mime"`
	Size       int64  `json:"size"`
	UploadedBy int64  `json:"uploaded_by"`
	Alt        string `json:"alt"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Key,
		arg.Filename,
		arg.Url,
		arg.Mime,
		arg.Size,
		arg.UploadedBy,
		arg.Alt,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.Url,
		&i.Mime,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Alt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, "key", filename, url, mime, size, uploaded_by, created_at, alt FROM media WHERE id = ?
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.Url,
		&i.Mime,
		&i.Size,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.Alt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, "key", filename, url, mime, size, uploaded_by, created_at, alt FROM media ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMediaParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Filename,
			&i.Url,
			&i.Mime,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.Alt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaAlt = `-- name: UpdateMediaAlt :exec
UPDATE media SET alt = ? WHERE id = ?
`

type UpdateMediaAltParams struct {
	Alt string `json:"alt"`
	ID  int64  `json:"id"`
}

func (q *Queries) UpdateMediaAlt(ctx context.Context, arg UpdateMediaAltParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaAlt, arg.Alt, arg.ID)
	return err
}
