// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type ApiKey struct {
	ID         int64      `json:"id"`
	Name       string     `json:"name"`
	KeyHash    string     `json:"key_hash"`
	CreatedBy  int64      `json:"created_by"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Medium struct {
	ID         int64     `json:"id"`
	Key        string    `json:"key"`
	Filename   string    `json:"filename"`
	Url        string    `json:"url"`
	Mime       string    `json:"mime"`
	Size       int64     `json:"size"`
	UploadedBy int64     `json:"uploaded_by"`
	CreatedAt  time.Time `json:"created_at"`
	Alt        string    `json:"alt"`
}

type Post struct {
	ID               int64      `json:"id"`
	Uuid             string     `json:"uuid"`
	Type             string     `json:"type"`
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	Markdown         string     `json:"markdown"`
	Html             string     `json:"html"`
	Excerpt          string     `json:"excerpt"`
	FeatureImage     string     `json:"feature_image"`
	Status           string     `json:"status"`
	Visibility       string     `json:"visibility"`
	AuthorID         int64      `json:"author_id"`
	PublishedAt      *time.Time `json:"published_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	Lang             string     `json:"lang"`
	TranslationGroup string     `json:"translation_group"`
}

type PostRevision struct {
	ID        int64     `json:"id"`
	PostID    int64     `json:"post_id"`
	Title     string    `json:"title"`
	Markdown  string    `json:"markdown"`
	AuthorID  int64     `json:"author_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PostTag struct {
	PostID   int64 `json:"post_id"`
	TagID    int64 `json:"tag_id"`
	Position int64 `json:"position"`
}

type PostsFt struct {
	Title    string `json:"title"`
	Markdown string `json:"markdown"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tag struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type TagTranslation struct {
	TagID       int64  `json:"tag_id"`
	Lang        string `json:"lang"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	Bio          string    `json:"bio"`
	ImageUrl     string    `json:"image_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Locale       string    `json:"locale"`
}
