// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package db

import (
	"context"
	"time"
)

const createRevision = `-- name: CreateRevision :exec
INSERT INTO post_revisions (post_id, title, markdown, author_id) VALUES (?, ?, ?, ?)
`

type CreateRevisionParams struct {
	PostID   int64  `json:"post_id"`
	Title    string `json:"title"`
	Markdown string `json:"markdown"`
	AuthorID int64  `json:"author_id"`
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createRevision,
		arg.PostID,
		arg.Title,
		arg.Markdown,
		arg.AuthorID,
	)
	return err
}

const deleteRevisionsBelowID = `-- name: DeleteRevisionsBelowID :exec
DELETE FROM post_revisions WHERE post_id = ? AND id <
`

type DeleteRevisionsBelowIDParams struct {
	PostID int64 `json:"post_id"`
	ID     int64 `json:"id"`
}

// Prunes a post's history. Ids are monotonic, so "older than the oldest one we
// are keeping" is just an id comparison — sqlc's SQLite parser rejects the
// self-referencing subquery a single-statement trim would need.
func (q *Queries) DeleteRevisionsBelowID(ctx context.Context, arg DeleteRevisionsBelowIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteRevisionsBelowID, arg.PostID, arg.ID)
	return err
}

const getRevision = `-- name: GetRevision :one
SELECT id, post_id, title, markdown, author_id, created_at FROM post_revisions WHERE id = ?
`

func (q *Queries) GetRevision(ctx context.Context, id int64) (PostRevision, error) {
	row := q.db.QueryRowContext(ctx, getRevision, id)
	var i PostRevision
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Title,
		&i.Markdown,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.post_id, r.title, r.created_at, u.name AS author_name
FROM post_revisions r JOIN users u ON u.id = r.author_id
WHERE r.post_id = ?
ORDER BY r.created_at DESC
LIMIT ?
`

type ListRevisionsParams struct {
	PostID int64 `json:"post_id"`
	Limit  int64 `json:"limit"`
}

type ListRevisionsRow struct {
	ID         int64     `json:"id"`
	PostID     int64     `json:"post_id"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	AuthorName string    `json:"author_name"`
}

func (q *Queries) ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions, arg.PostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevisionsRow{}
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Title,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
