// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"time"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO post_tags (post_id, tag_id, position) VALUES (?, ?, ?)
ON CONFLICT (post_id, tag_id) DO UPDATE SET position = excluded.position
`

type AddPostTagParams struct {
	PostID   int64 `json:"post_id"`
	TagID    int64 `json:"tag_id"`
	Position int64 `json:"position"`
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.ExecContext(ctx, addPostTag, arg.PostID, arg.TagID, arg.Position)
	return err
}

const clearPostTags = `-- name: ClearPostTags :exec
DELETE FROM post_tags WHERE post_id = ?
`

func (q *Queries) ClearPostTags(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, clearPostTags, postID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug, description) VALUES (?, ?, ?) RETURNING id, name, slug, description, created_at
`

type CreateTagParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Slug, arg.Description)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, slug, description, created_at FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, description, created_at FROM tags WHERE slug = ?
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPostTags = `-- name: ListPostTags :many
SELECT t.id, t.name, t.slug, t.description, t.created_at FROM tags t
JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = ?
ORDER BY pt.position
`

func (q *Queries) ListPostTags(ctx context.Context, postID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listPostTags, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, t.slug, t.description, t.created_at, (SELECT count(*) FROM post_tags pt WHERE pt.tag_id = t.id) AS post_count
FROM tags t
ORDER BY t.name
`

type ListTagsRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	PostCount   int64     `json:"post_count"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagSlugExists = `-- name: TagSlugExists :one
SELECT EXISTS (SELECT 1 FROM tags WHERE slug = ?)
`

func (q *Queries) TagSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, tagSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tagSlugExistsExcept = `-- name: TagSlugExistsExcept :one
SELECT EXISTS (SELECT 1 FROM tags WHERE slug = ? AND id <> ?)
`

type TagSlugExistsExceptParams struct {
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

func (q *Queries) TagSlugExistsExcept(ctx context.Context, arg TagSlugExistsExceptParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, tagSlugExistsExcept, arg.Slug, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = ?, slug = ?, description = ? WHERE id = ? RETURNING id, name, slug, description, created_at
`

type UpdateTagParams struct {
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
