// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: translations.sql

package db

import (
	"context"
	"time"
)

const deleteTagTranslation = `-- name: DeleteTagTranslation :exec
DELETE FROM tag_translations WHERE tag_id = ? AND lang = ?
`

type DeleteTagTranslationParams struct {
	TagID int64  `json:"tag_id"`
	Lang  string `json:"lang"`
}

func (q *Queries) DeleteTagTranslation(ctx context.Context, arg DeleteTagTranslationParams) error {
	_, err := q.db.ExecContext(ctx, deleteTagTranslation, arg.TagID, arg.Lang)
	return err
}

const getTranslation = `-- name: GetTranslation :one
SELECT id, uuid, type, title, slug, markdown, html, excerpt, feature_image, status, visibility, author_id, published_at, created_at, updated_at, lang, translation_group FROM posts WHERE translation_group = ? AND lang = ?
`

type GetTranslationParams struct {
	TranslationGroup string `json:"translation_group"`
	Lang             string `json:"lang"`
}

func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getTranslation, arg.TranslationGroup, arg.Lang)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Markdown,
		&i.Html,
		&i.Excerpt,
		&i.FeatureImage,
		&i.Status,
		&i.Visibility,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Lang,
		&i.TranslationGroup,
	)
	return i, err
}

const listPostTagsLabelled = `-- name: ListPostTagsLabelled :many
SELECT t.id, t.name, t.slug, t.description, t.created_at, COALESCE(tt.name, t.name) AS label
FROM tags t
JOIN post_tags pt ON pt.tag_id = t.id
LEFT JOIN tag_translations tt ON tt.tag_id = t.id AND tt.lang = ?
WHERE pt.post_id = ?
ORDER BY pt.position
`

type ListPostTagsLabelledParams struct {
	Lang   string `json:"lang"`
	PostID int64  `json:"post_id"`
}

type ListPostTagsLabelledRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	Label       string    `json:"label"`
}

func (q *Queries) ListPostTagsLabelled(ctx context.Context, arg ListPostTagsLabelledParams) ([]ListPostTagsLabelledRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostTagsLabelled, arg.Lang, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostTagsLabelledRow{}
	for rows.Next() {
		var i ListPostTagsLabelledRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagTranslations = `-- name: ListTagTranslations :many
SELECT tag_id, lang, name, description FROM tag_translations WHERE tag_id = ? ORDER BY lang
`

func (q *Queries) ListTagTranslations(ctx context.Context, tagID int64) ([]TagTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listTagTranslations, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagTranslation{}
	for rows.Next() {
		var i TagTranslation
		if err := rows.Scan(
			&i.TagID,
			&i.Lang,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsLabelled = `-- name: ListTagsLabelled :many
SELECT t.id, t.name, t.slug, t.description, t.created_at, COALESCE(tt.name, t.name) AS label,
       (SELECT count(*) FROM post_tags pt WHERE pt.tag_id = t.id) AS post_count
FROM tags t
LEFT JOIN tag_translations tt ON tt.tag_id = t.id AND tt.lang = ?
ORDER BY label
LIMIT ? OFFSET ?
`

type ListTagsLabelledParams struct {
	Lang   string `json:"lang"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListTagsLabelledRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	Label       string    `json:"label"`
	PostCount   int64     `json:"post_count"`
}

// Tags labelled for one language, falling back to the tag's own name so an
// untranslated tag still reads as something.
func (q *Queries) ListTagsLabelled(ctx context.Context, arg ListTagsLabelledParams) ([]ListTagsLabelledRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsLabelled, arg.Lang, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsLabelledRow{}
	for rows.Next() {
		var i ListTagsLabelledRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.Label,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslations = `-- name: ListTranslations :many

SELECT id, lang, slug, title, status, type
FROM posts
WHERE translation_group = ? AND translation_group <> ''
ORDER BY lang
`

type ListTranslationsRow struct {
	ID     int64  `json:"id"`
	Lang   string `json:"lang"`
	Slug   string `json:"slug"`
	Title  string `json:"title"`
	Status string `json:"status"`
	Type   string `json:"type"`
}

// Keep comments in this directory ASCII-only; see revisions.sql for why.
// Siblings of a post, itself included, so the editor can offer the languages
// that already exist and the ones that do not.
//
// The empty group is excluded deliberately. A row written without one would
// otherwise be a sibling of every other such row, which silently links posts
// that have nothing to do with each other.
func (q *Queries) ListTranslations(ctx context.Context, translationGroup string) ([]ListTranslationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTranslations, translationGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranslationsRow{}
	for rows.Next() {
		var i ListTranslationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Lang,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTagTranslation = `-- name: SetTagTranslation :exec
INSERT INTO tag_translations (tag_id, lang, name, description) VALUES (?, ?, ?, ?)
ON CONFLICT (tag_id, lang) DO UPDATE
SET name = excluded.name, description = excluded.description
`

type SetTagTranslationParams struct {
	TagID       int64  `json:"tag_id"`
	Lang        string `json:"lang"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) SetTagTranslation(ctx context.Context, arg SetTagTranslationParams) error {
	_, err := q.db.ExecContext(ctx, setTagTranslation,
		arg.TagID,
		arg.Lang,
		arg.Name,
		arg.Description,
	)
	return err
}
